dist: bionic

language: go

before_install:
  # install docker-compose and run our backend containers
  - sudo apt update
  - sudo apt upgrade
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable edge"
  - sudo apt install docker-ce
  - sudo systemctl status docker
  - docker --version
  - docker-compose -f docker-compose-backend.yml up --detach

go:
  - 1.15.x

install:
  - go build

script:
  - go test ./... -v
  - docker-compose down
  - go build

jobs:
  include:
    - stage: test
      script:
        - go test ./...
        - docker-compose down
    - stage: build
      script:
        - go build
