dist: bionic

language: go

before_install:
  - sudo apt update
  - sudo apt upgrade
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable edge"
  - sudo apt install docker-ce
  - sudo systemctl status docker
  - docker --version
  - docker-compose up --detach

go:
  - 1.14.x

install:
  - go build

script:
  - go test ./...
  - docker-compose down
  - go build
