dist: bionic

language: go

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - wget https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_20.10.2~3-0~ubuntu-bionic_amd64.deb -O docker.deb
  - sudo dpkg -i docker.deb

go:
  - 1.14.x

install:
  - go build

script:
  - go test ./...
  - go build
